Fixed problem when running in Jetty. Jetty doesn't provide Java EE 5 JARs so we were getting java.lang.NoClassDefFoundError: javax/annotation/Resource exceptions.